# Hibernate & MySQL configuration
hibernate.connection.driver_class=com.mysql.cj.jdbc.Driver
hibernate.connection.url=jdbc:mysql://localhost:3306/exercice3
hibernate.connection.username=YOUR_USER
hibernate.connection.password=YOUR_PASSWORD
hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
hibernate.hbm2ddl.auto=update
hibernate.show_sql=true
hibernate.format_sql=true
